import streamlit as st
st.title("jojo")
st.header("jojo")
st.subheader("jojo")
st.write("jojo")
st.text("jojo")
st.markdown("jojo")
st.latex("jojo")
st.code("jojo")
st.error("jojo")
st.warning("jojo")
st.info("jojo")
st.success("jojo")
st.exception(Exception("jojo"))
