import streamlit as st
st.title("jojo ghogho")
st.header("jojo ghogho")
st.subheader("jojo ghogho")
st.write("jojo ghogho")
st.text("jojo ghogho")
st.markdown("jojo ghogho")
st.latex("jojo ghogho")
st.code("jojo ghogho")
st.error("jojo ghogho")
st.warning("jojo ghogho")
st.info("jojo ghogho")
st.success("jojo ghogho")
st.exception(Exception("jojo ghogho"))